[pytest]
testpaths = tests/
python_files=*.py
python_functions=test_*
markers =
    unit: unit tests
filterwarnings =
    error::pytest.PytestUnknownMarkWarning
addopts = -rxX
          --capture=no
          --verbose
          --showlocals
          --tb=long
          --cov=speedtest
          -p no:warnings
